name: Tests
on:
  push:
    branches:
      - master
      - testnet/3
  pull_request:
    branches:
      - master
      - tesntet/3
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: go build ./...
